version: "3.3"

services:
  library-db:
    restart: always
    image: sameersbn/postgresql:10-2
    environment:
      - PG_TRUST_LOCALNET=true
      - DB_NAME=library
      - DB_USER=postgres
      - DB_PASS=postgres
      - PG_RUNDIR=/run/postgres
      - PG_LOGDIR=/var/log/mostgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/library/postgresql
      - logs:/var/log/postgresql

  keycloak:
    restart: always
    image: quay.io/keycloak/keycloak:18.0.0
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8090:8080"

  docker-demo:
    image: bibisvk/docker-demo
    ports:
      - "8080:8080"

  pozicovna-aut:
    image: pozicovna-aut
    ports:
      - "80:80"

volumes:
  data:
  logs: